Loading data...
Using  cuda
Training...
Process Process-1:
Traceback (most recent call last):
  File "/usr/common/software/pytorch/v1.2.0-gpu/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/common/software/pytorch/v1.2.0-gpu/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/global/homes/d/danieltm/.local/cori/pytorchv1.2.0-gpu/lib/python3.6/site-packages/wandb/wandb_agent.py", line 63, in _start
    function()
  File "edge_sweep.py", line 212, in train
    val_acc, val_loss = edge_validate(model, val_loader, 20, device)
TypeError: edge_validate() takes 3 positional arguments but 4 were given
